# Config file for Upgrades addon

# Disabled Game Mode Addons
# IslandUpgrades will not work in these game modes
disabled-gamemodes: []

# Range Upgrade Default Tiers
# Each tier must contain:
#      max-level: Upgrade level up to which tier apply
#      upgrade-range: How much block is added to the range with each upgrade
#      island-min-level: Minimum level required to upgrade (if level addon is provided)
#      vault-cost: Money cost of upgrade
# Note: for upgrade-range, island-min-level and vault-cost:
#      Mathematical expression can be used (+,-,*,/,^,(,))
#      Mathematical function can be used (sqrt,sin,cost,tan)
#      Special value can be used:
#         [level] : Is the actual level for this upgrade
#         [islandLevel] : Is the islandLevel from level addon
#         [numberPlayer] : Is the number of players in team
#
# Caution: You should always check that at max level, your players won't attain max range for island
range-upgrade:
  tier1:
    max-level: 5
    upgrade: "5"
    island-min-level: "2"
    vault-cost: "[level]*100"
  tier2:
    max-level: 10
    upgrade: "3"
    island-min-level: "4"
    vault-cost: "[level]*[numberPlayer]*200"

block-limits-upgrade:
  HOPPER:
    tier1:
      max-level: 2
      upgrade: "1"
      island-min-level: "2"
      vault-cost: "[level]*100"
    tier2:
      max-level: 5
      upgrade: "1"
      island-min-level: "4"
      vault-cost: "([level]-2)*[numberPlayer]*700"

entity-limits-upgrade:
  CHICKEN:
    tier1:
      max-level: 2
      upgrade: "1"
      island-min-level: "2"
      vault-cost: "[level]*100"
    tier2:
      max-level: 5
      upgrade: "1"
      island-min-level: "4"
      vault-cost: "([level]-2)*[numberPlayer]*700"

# GameMode differences
# List any tiers that you want to add
# You can overwrite a tier by using the same name
gamemodes:
  BSkyBlock:

    range-upgrade:
      tier3:
        max-level: 15
        upgrade: "5"
        island-min-level: "6"
        vault-cost: "[level]*[numberPlayer]*500"

    block-limits-upgrade:
      HOPPER:
        tier1:
          max-level: 2
          upgrade: "1"
          island-min-level: "2"
          vault-cost: "[level]*200"

    entity-limits-upgrade:
      CHICKEN:
        tier1:
          max-level: 2
          upgrade: "1"
          island-min-level: "2"
          vault-cost: "[level]*200"

entity-icon:
  CHICKEN: CHICKEN_SPAWN_EGG